### ISSUE TITLE
Documentation typo (Linux audit)

### ISSUE THREAD

**Issue by BlueDrink9** [ashish-gehani/SPADE#101]
On [this wiki page](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Linux-with-Audit) the audit config path is

`/etc/audisp/plugins.d/af_unix.conf`. That should probably be  
`/etc/audit/plugins.d/af_unix.conf`

**Comment by ashish-gehani** [comment]
It is correct as is. See: https://packages.ubuntu.com/focal/i386/auditd/filelist

**Comment by BlueDrink9** [comment]
Interesting, on my [fedora vm](https://github.com/CamFlow/vagrant/blob/headless-boxes/spade/Vagrantfile) that folder and file didn't exist, but the one I suggested did. Maybe add it as a caveat?

**Comment by ashish-gehani** [comment]
Thanks. Updated.
