### ISSUE TITLE
How do I get started?

### ISSUE THREAD

**Issue by bronzeMe** [ashish-gehani/SPADE#102]
Hi, I am a fresher to SPADE, I have compiled it  successfully on the Ubutnu 16.04 (64bit).
I tried it as the following steps:
(1) startup spade
 ```
./spade start
nohup: redirecting stderr to stdout
Running SPADE with PID = 9427
```
(2) startup spade control
```
 ./spade control

SPADE 3.0 Control Client

Available commands:
	add reporter|storage <class name> <initialization arguments>
	add analyzer|sketch <class name>
	add filter|transformer <class name> position=<number> <initialization arguments>
	set storage <class name>
	remove reporter|analyzer|storage|sketch <class name>
	remove filter|transformer <position number>
	list reporters|storages|analyzers|filters|sketches|transformers|all
	config load|save <filename>
	exit
```
(3) add storage Neo4j
```
-> add storage Neo4j database=/tmp/graph.db
Adding storage Neo4j... done
```
(4) run Neo4j server by running `bin/neo4j` start command 
the config file of Neo4j:` lib/neo4j-community-3.4.4/conf/neo4j.conf`
I have edited the file `lib/neo4j-community-3.4.4/conf/neo4j.conf` and set `dbms.active_database to` the `/tmp/graph.db`.
Then, startup the Neo4J server as the following:
```
 ./neo4j start
Active database: /tmp/graph.db
Directories in use:
  home:         /xx/SPADE-master/lib/neo4j-community-3.4.4
  config:       /xx/SPADE-master/lib/neo4j-community-3.4.4/conf
  logs:         /xx/SPADE-master/lib/neo4j-community-3.4.4/logs
  plugins:      /xx/SPADE-master/lib/neo4j-community-3.4.4/plugins
  import:       /xx/SPADE-master/lib/neo4j-community-3.4.4/import
  data:         /xx/SPADE-master/lib/neo4j-community-3.4.4/data
  certificates: /xx/SPADE-master/lib/neo4j-community-3.4.4/certificates
  run:          /xx/SPADE-master/lib/neo4j-community-3.4.4/run
Starting Neo4j.
WARNING: Max 1024 open files allowed, minimum of 40000 recommended. See the Neo4j manual.
Started neo4j (pid 11598). It is available at http://localhost:7474/
There may be a short delay until the server is ready.
See /xx/SPADE-master/lib/neo4j-community-3.4.4/logs/neo4j.log for current status.
```

(5) configuring JSON reporter following the [link](https://github.com/ashish-gehani/SPADE/wiki/Reporting-provenance-using-JSON)
```
add reporter JSON /tmp/provenance.json
Adding reporter JSON... done
```
(6) **however, when I tried to query something in the database, there is nothing !**
(6.1) when executing `MATCH (n:VERTEX) RETURN n`:

![image](https://user-images.githubusercontent.com/11402109/85970099-fb2a3a80-b9fb-11ea-884e-283c45ea7174.png)

(6.2)  Count all nodes
![image](https://user-images.githubusercontent.com/11402109/85970137-172ddc00-b9fc-11ea-94e4-1c5ec79ea764.png)

Could someone give some advice? Thanks .

By the way, the pictures in the Wiki documents are unavailable, it is a nice work if someone can update them!

**Comment by hassaanirshad** [comment]
Thank you for sharing the detailed description of the steps. Can you please inspect the log generated by SPADE in the 'log' directory for any errors? If you don't see any errors then can you please share the log?

Also, can you please tell me which wiki documents have unavailable pictures?

**Comment by bronzeMe** [comment]
@hassaanirshad  Hi, thank you for your reply , when I executed the command `add reporter JSON /tmp/provenance.json` the spade threw some errors:
```
Jun 30, 2020 8:31:32 AM spade.core.Kernel addCommand INFO: Adding reporter: JSON
Jun 30, 2020 8:31:32 AM spade.core.Kernel addCommand INFO: Reporter added: JSON /tmp/provenance.json
Jun 30, 2020 8:31:32 AM spade.reporter.JSON log INFO: Starting to read json file
Jun 30, 2020 8:31:32 AM spade.reporter.JSON log INFO: Sucessfully read json file
Jun 30, 2020 8:31:32 AM spade.reporter.JSON log INFO: Starting to objectify JSON content
Jun 30, 2020 8:31:32 AM spade.reporter.JSON log INFO: Sucessfully objectified JSON content
Jun 30, 2020 8:31:32 AM spade.reporter.JSON log INFO: Size of JSON Array: 3
Jun 30, 2020 8:31:32 AM spade.reporter.JSON log INFO: All provenance reported through JSON file has been retrived. Wait for buffers to clear....
Jun 30, 2020 8:31:32 AM spade.core.Kernel$1 run SEVERE: Error registering Main Thread
org.neo4j.kernel.impl.core.ThreadToStatementContextBridge$BridgeNotInTransactionException: The requested operation cannot be performed, because it has to be performed in a transaction. Ensure you are wrapping your operation in the appropriate transaction boilerplate and try again.
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.assertInUnterminatedTransaction(ThreadToStatementContextBridge.java:73)
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getTopLevelTransactionBoundToThisThread(ThreadToStatementContextBridge.java:107)
	at org.neo4j.kernel.impl.core.ThreadToStatementContextBridge.getKernelTransactionBoundToThisThread(ThreadToStatementContextBridge.java:115)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.lambda$null$1(GraphDatabaseFacade.java:218)
	at org.neo4j.kernel.impl.coreapi.ExplicitIndexProxy.get(ExplicitIndexProxy.java:284)
	at spade.storage.Neo4j.putEdge(Neo4j.java:432)
	at spade.filter.FinalCommitFilter.putEdge(FinalCommitFilter.java:55)
	at spade.core.Kernel$1.run(Kernel.java:560)
	at java.lang.Thread.run(Thread.java:748)

Jun 30, 2020 8:31:33 AM spade.reporter.JSON log INFO: Size of buffer: 0
Jun 30, 2020 8:31:33 AM spade.reporter.JSON log INFO: All buffers cleared. You may remove JSON reporter
```

**Comment by BlueDrink9** [comment]
I wonder if this is an issue with the Neo4J storage/browser. I'm also not getting anything in the browser with the audit reporter, but the dot graph and created pdf from the same output is full, and the neo4j database is 23 mb so clearly has something in it.

Try adding a dot/graphviz reporter and seeing if that ends up with any nodes in it.

**Comment by hassaanirshad** [comment]
@bronzeMe Can you please share the java version that you are using? I am unable to reproduce the error (using Neo4j storage) on openjdk8 and openjdk10.

**Comment by bronzeMe** [comment]
@hassaanirshad Hi,
The java version is :
```
java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~16.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

**Comment by bronzeMe** [comment]
@BlueDrink9 ,thanks your comments, could you please give more detail?

**Comment by hassaanirshad** [comment]
@bronzeMe Thank you for sharing that. Can you please try connecting to the Neo4j database (using the browser) after it is has been removed from SPADE using the command `remove storage Neo4j`? The issue might be Neo4j database lock contention between the Neo4j browser and SPADE.

**Comment by BlueDrink9** [comment]
I mean try adding a second storage, [for example graphviz](https://github.com/ashish-gehani/SPADE/wiki/Creating-Graphviz-output), then re-running it. See if the second storage *does* have data, while the neo4j one looks empty. That would help identify where the issue lies.

**Comment by hassaanirshad** [comment]
Closed because of inactivity.

**Comment by BlueDrink9** [comment]
As a note, I tried accessing neo4j after removing it as a storage in SPADE, and still got no results. There must be data in the DB though, because it shows up in `spade query`

**Comment by hassaanirshad** [comment]
@BlueDrink9 Please check out this [issue](https://github.com/ashish-gehani/SPADE/issues/104) to possibly resolve what you mentioned.
