### ISSUE TITLE
Spade query has error in suggestion for 'force dump' (or seems to)

### ISSUE THREAD

**Issue by BlueDrink9** [ashish-gehani/SPADE#103]
In `spade query`, trying to `dump $base` fails with export limit. The suggestion given is to "Please use 'force dump ...' to force the print". This fails. `dump force` succeeds, so I presume the error message should be changed.

(Also, it would be good to document in the query page that `dump $base` is the way to dump the whole db, which is useful for debugging).

```
-> dump $base
Error: Error evaluating QuickGrail command:
------------------------------------------------------------
Dump export limit set at '4096'. Total vertices and edges requested '14632'.Please use 'force dump ...' to force the print.
------------------------------------------------------------

-> export > /tmp/query_graph_base
Output export path set to '/tmp/query_graph_base' for next query.
-> force dump $base
Error: Error evaluating QuickGrail command:
------------------------------------------------------------
Unsupported command "force" at line 1, column 0
------------------------------------------------------------

-> dump force $base
[succeeds]
```

**Comment by hassaanirshad** [comment]
Thank you for pointing that out and will be updated. And as for `dump $base` it is mentioned [here](https://github.com/ashish-gehani/SPADE/blob/master/src/spade/query/quickgrail/README.md) that `$base` represents the whole graph.

**Comment by BlueDrink9** [comment]
Yeah, that's where I saw `$base` used. I think it would be good to include it as an example on [this wiki page](https://github.com/ashish-gehani/SPADE/wiki/Querying-SPADE), since that's where I mostly started looking.

**Comment by hassaanirshad** [comment]
Thank you. Description of `$base` has been added to the wiki page [Querying SPADE](https://github.com/ashish-gehani/SPADE/wiki/Querying-SPADE).
