### ISSUE TITLE
Documentation Update | Viewing/ Storing provenance in a graph database

### ISSUE THREAD

**Issue by StarFir3** [ashish-gehani/SPADE#104]
## Problem

In the document [Storing provenance in a Neo4j graph database](https://github.com/ashish-gehani/SPADE/wiki/Storing-provenance-in-a-Neo4j-graph-database) 

The database is added at /tmp/spade.graph_db

![image](https://user-images.githubusercontent.com/46611115/86270758-aafdd480-bbc3-11ea-9b8a-65e28a9cfd1c.png)

^ This creates a folder in the `/tmp` directory of the host machine.

In the document of [viewing provenance in a graph database](https://github.com/ashish-gehani/SPADE/wiki/Viewing-provenance-in-a-graph-database) `dbms.active_database` is set to the location of your Neo4j database; which is probably wrong. When we set the `dbms.active_database` to `/tmp/spade.graph_db`, it searches for that database in the `data/databases` directory rather than `/tmp/spade.graph_db`

## Solution

Ideally, database should be created in the location where neo4j databases are stored such as `/home/vagrant/SPADE/lib/neo4j-community-3.4.4/data/databases` and then `spade.graph_db` so full location should be `/home/vagrant/SPADE/lib/neo4j-community-3.4.4/data/databases/spade.graph_db`

If the neo4j is installed system-wide, the location should be `/var/lib/neo4j/data/databases` and then `spade.graph_db`. 

By default, we should specify the name of the active database such as `dbms.active_database=spade.graph_db` and neo4j automatically locates the location of the database in the `data/database` folder. 

## Tested

If we add ne04j storage with this particular path

![image](https://user-images.githubusercontent.com/46611115/86270940-fa440500-bbc3-11ea-9cde-ec26e2c343b9.png)

 And set dbms.active=spade

![image](https://user-images.githubusercontent.com/46611115/86270956-ffa14f80-bbc3-11ea-96a2-6fd924bdee02.png)

It will directly go to the database and and then loads the database.

**Comment by hassaanirshad** [comment]
Thank you for pointing out the issue. The issue has been fixed using the solution proposed with some differences. 

Before using the Neo4j storage please review the wiki pages: 1) [Storing provenance in a Neo4j graph database](https://github.com/ashish-gehani/SPADE/wiki/Storing-provenance-in-a-Neo4j-graph-database), and 2) [Viewing provenance in a graph database](https://github.com/ashish-gehani/SPADE/wiki/Viewing-provenance-in-a-graph-database)

**Comment by BlueDrink9** [comment]
It would be very desirable for users to be able to set the database location absolutely, for example if they need the database to be on a networked disk seperate to SPADE for backup reasons.

Might a solution be to have symlink it into the neo4j `databases/` dir? Maybe have a db ID for each DB location the user adds (possibly based off the desired path) to use as the symlink name.

For example, a user adds their database at `/mnt/backup/prov.graph_db`, and in the background SPADE symlinks it into `lib/neo4j-community-3.4.4/data/mnt%backup%prov.graph_db`?
