### ISSUE TITLE
SPADE Neo4j data format | Update required

### ISSUE THREAD

**Issue by StarFir3** [ashish-gehani/SPADE#105]
## Problem

If we install neo4j latest version installed by either source/ repository. The Neo4j is unable to read the SPADE database.

Currently, Spade writes the graph database in neo4j record format standard v3.4.4. However, the latest standard is 4.0.0.

If we want to read the SPADE graphdb in latest neo4j, we can uncomment the auto upgrade option. However, if we do that the SPADE won't be able to write into the database again.

![image](https://user-images.githubusercontent.com/46611115/86275036-8d803900-bbca-11ea-934f-310ce00b34f9.png)

## Suggestion

- Update SPADE code to write the database into the newer format.
- If we do the above, maybe suggest to install the neo4j from the sources and update the documents for the same.

**Comment by hassaanirshad** [comment]
The Neo4j storage has been updated to use Neo4j Community version 4.1.1 (current release). And the mentioned property `dbms.allow_upgrade` can be toggled by updating the file [cfg/neo4j.properties](https://github.com/ashish-gehani/SPADE/blob/master/cfg/neo4j.properties#L9).
