### ISSUE TITLE
Document which storage backends work with querying

### ISSUE THREAD

**Issue by BlueDrink9** [ashish-gehani/SPADE#107]
I tried using querying with the Graphviz and H2 storage engines. Neither, apparently, support querying according to error messages received when trying to configure them for such.

I could not find mention of this in the wiki, so can I please suggest in [Querying SPADE](https://github.com/ashish-gehani/SPADE/wiki/Querying-SPADE) that the backends that support it (or the ones that don't) are documented.

**Comment by ashish-gehani** [comment]
Done. Thank you for pointing this out.
