### ISSUE TITLE
Null Pointer Thrown out In Sanitization Transformer

### ISSUE THREAD

**Issue by Andercxt** [ashish-gehani/SPADE#109]
I got a "Error: Failed to execute query: Sanitization'" problem when using Sanitization Transformer to do the query. The steps to reproduce the problem is as follows.

Overall, I was using the VM generated by the vagrant box of SPADE. In the control panel opened by "./bin/spade control".

1.  add analyzer CommandLine
2.  add storage Neo4j
3.  add reporter Audit unixSockets=true fileIO=true netIO=true handleLocalEndpoints=true handleNetfilterHooks=true reportIpc=true namespaces=true inputLog=/home/vagrant/ls.log
4. remove reporter Audit
5. add transformer Sanitization sanitizationLevel=low position=1
6. exit

In the query panel opened by "./bin/spade query".

1. set storage Neo4j
2. export > /home/vagrant/sanitization&encryption/lowsanitized.txt
3. dump force $base

The "/home/vagrant/ls.log" is available through this link: 
[ls.log](https://github.com/ashish-gehani/SPADE/files/6131477/ls.log)

And the corresponding SPADE error log is here: 
[SPADE_03.08.2021-14.21.23.log](https://github.com/ashish-gehani/SPADE/files/6131479/SPADE_03.08.2021-14.21.23.log)

**Comment by hassaanirshad** [comment]
Thank you for sharing the detailed information about the issue.

Please pull the latest code in the 'master' branch for the fix and retry the steps mentioned in the issue.

The fix merged into the 'master' branch from the 'privacy-dev' branch pushed by @sranasir.
