### ISSUE TITLE
`make install` errors

### ISSUE THREAD

**Issue by TomMD** [ashish-gehani/SPADE#11]
After a fresh pull, `./configure` and `make` I see:

```
$ sudo make install
/bin/sh: 1: pkg-config: not found
test -d /usr/local || mkdir /usr/local
cp -R bin /usr/local
cp -R lib /usr/local
cp -R cfg /usr/local
cp -R log /usr/local
cp: cannot stat ‘log’: No such file or directory
```

Perhaps the makefile should include `mkdir -p log` or the git repo should include a dummy file in the `log` directory to ensure it exists (since git can't track existence of empty directories).

**Comment by hasanatkazmi** [comment]
Please pull latest push
