### ISSUE TITLE
Unable to add reporter

### ISSUE THREAD

**Issue by Hare-Lucius** [ashish-gehani/SPADE#113]
I have two problems which I hope you can do me a favour. I use Ubuntu 20.04.
First,  I download SPADE on 20th May, and I encounter a problem that I cannot collect information with Audit and fileIO=true setted. I'm sorry no useful log can be offered in this case because there is no exception.
To be more specific, when I successfully set `add reporter Audit netIO=true, add storage Neo4j database=data` and visit a website, I can find new data stored into Neo4j. So SPADE works well in netIO situation.
But when I successfully set `add reporter Audit fileIO=true, add storage Neo4j database=data` and execute a process which writes a file, no new data can be found in Neo4j. But in fact, system call 'write' should be recored.
Second, after I update SPADE on 1st June, I cannot add reporter any more. 
`add reporter Audit
Adding reporter Audit... failed`
The log is here.
`	at spade.reporter.Audit._launch(Audit.java:307)
	at spade.reporter.Audit.launch(Audit.java:277)
	at spade.core.Kernel.addReporterCommand(Kernel.java:1028)
	at spade.core.Kernel.addCommand(Kernel.java:1192)
	at spade.core.Kernel.executeCommand(Kernel.java:621)
	at spade.core.Kernel$LocalControlConnection.run(Kernel.java:2059)
	at java.base/java.lang.Thread.run(Thread.java:829)

Jun 02, 2021 1:36:16 AM spade.reporter.Audit launch SEVERE: Failed to launch reporter
Jun 02, 2021 1:36:16 AM spade.core.Kernel addReporterCommand SEVERE: Unable to launch reporter
`

**Comment by hassaanirshad** [comment]
The beginning of the error message is truncated, and therefore doesn't contain the relevant information.

You can attached the full SPADE log (which contains the error) as a gzipped file in the reply.

**Comment by Hare-Lucius** [comment]
Here's the complete log below(about Problem 2).

`Jun 02, 2021 12:33:57 PM spade.core.Kernel getHostName INFO: SPADE host name: 'ubuntu'
Jun 02, 2021 12:33:57 PM spade.core.Kernel addStorageCommand INFO: Adding storage: Neo4j
Jun 02, 2021 12:33:57 PM spade.screen.Deduplicate loadBloomFilterAndCache INFO: Vertex BloomFilter initialized from arguments: [falsePositiveProbability=0.000000100, expectedElements=1000000]
Jun 02, 2021 12:33:57 PM spade.screen.Deduplicate loadBloomFilterAndCache INFO: Vertex BloomFilter would NOT be saved on shutdown
Jun 02, 2021 12:33:57 PM spade.screen.Deduplicate loadBloomFilterAndCache INFO: Vertex cache created with max size '10000'
Jun 02, 2021 12:33:57 PM spade.screen.Deduplicate loadBloomFilterAndCache INFO: Edge BloomFilter initialized from arguments: [falsePositiveProbability=0.000000100, expectedElements=1000000]
Jun 02, 2021 12:33:57 PM spade.screen.Deduplicate loadBloomFilterAndCache INFO: Edge BloomFilter would NOT be saved on shutdown
Jun 02, 2021 12:33:57 PM spade.screen.Deduplicate loadBloomFilterAndCache INFO: Edge cache created with max size '10000'
Jun 02, 2021 12:33:57 PM spade.screen.Deduplicate printStats INFO: verticesBlocked=0, verticesNotBlocked=0, edgesBlocked=0, edgesNotBlocked=0
Jun 02, 2021 12:33:57 PM spade.core.AbstractScreen initializeScreen INFO: Successfully initialized screen [name:spade.screen.Deduplicate, arguments:]
Jun 02, 2021 12:33:57 PM spade.storage.Neo4j initialize INFO: Configuration: dbms.directories.neo4j_home=/home/lby/Desktop/SPADE/lib/neo4j-community-4.1.1, database=data, dbms.default_database=neo4j, constructedDatabasePath=/home/lby/Desktop/SPADE/lib/neo4j-community-4.1.1/data/databases/neo4j, neo4jConfigFilePath=/home/lby/Desktop/SPADE/cfg/neo4j.properties, vertexCacheMode=NODE, edgeCacheFindMode=NONE, flushBufferSize=25000, flushAfterSeconds=60, bufferLimit=100000 (buffering:enabled), transactionTimeoutInSeconds=300 (limited:yes), forceShutdown=false, reset=false, maxRetries=10, waitForIndexSeconds=10, hashKeyCollisionAction=DISCARD, hashPropertyName=hash, edgeSymbolsPropertyName=spade_edge_symbols, nodePrimaryLabel=VERTEX (VERTEX), edgeRelationshipType=EDGE (EDGE), querySymbolsNodeLabel=spade_query_symbols (spade_query_symbols), index.vertex=ALL, index.edge=ALL, indexNamePrefix=spade_index_, reportingIntervalSeconds=120 (enabled), debug=false, timeMe=true, sleepWaitMillis=10, mainThreadSleepWaitMillis=0, test=false, test.vertex.total=0, test.edge.degree=0, test.vertex.annotations=[], test.edge.annotations=[], Ignored unexpected argument(s)={screen=Deduplicate}
Jun 02, 2021 12:34:02 PM spade.storage.Neo4j initialize INFO: Database absolute path: /home/lby/Desktop/SPADE/lib/neo4j-community-4.1.1/data/databases/neo4j
Jun 02, 2021 12:34:06 PM spade.core.Kernel addStorageCommand INFO: Storage added: class spade.storage.Neo4j database=data. Using screens: [Deduplicate]
Jun 02, 2021 12:34:12 PM spade.core.Kernel addReporterCommand INFO: Adding reporter: Audit
Jun 02, 2021 12:34:12 PM spade.core.BlockingBuffer log INFO: [Audit] workableFreeMemory=20.000%, reportingIntervalSeconds=120(enabled), sleepWaitMillis=1000
Jun 02, 2021 12:34:12 PM spade.core.Kernel addReporterCommand INFO: Memory usage limited buffer used for reporter 'Audit' with 'workableFreeMemory'='20' from '/home/lby/Desktop/SPADE/./cfg/spade.core.AbstractReporter.config'
Jun 02, 2021 12:34:12 PM spade.reporter.Audit _launch SEVERE: Failed to setup reporting
java.lang.Exception: Invalid value for key 'reportingIntervalSeconds'. Error: Not a long: NULL

	at spade.utility.profile.Intervaler.instance(Intervaler.java:73)
	at spade.reporter.Audit._launch(Audit.java:307)
	at spade.reporter.Audit.launch(Audit.java:277)
	at spade.core.Kernel.addReporterCommand(Kernel.java:1028)
	at spade.core.Kernel.addCommand(Kernel.java:1192)
	at spade.core.Kernel.executeCommand(Kernel.java:621)
	at spade.core.Kernel$LocalControlConnection.run(Kernel.java:2059)
	at java.base/java.lang.Thread.run(Thread.java:829)

Jun 02, 2021 12:34:12 PM spade.reporter.Audit launch SEVERE: Failed to launch reporter
Jun 02, 2021 12:34:12 PM spade.core.Kernel addReporterCommand SEVERE: Unable to launch reporter
`

**Comment by hassaanirshad** [comment]
There seems to be a mismatch between the version of your code, and the version of your Audit reporter configuration file `cfg/spade.reporter.Audit.config`. Please update your SPADE repo with the latest version.

According to the log, it is not able to find the argument `reportingIntervalSeconds` but the latest version expects the argument `reportingInterval` as specified [here](https://github.com/ashish-gehani/SPADE/blob/master/cfg/spade.reporter.Audit.config#L80).

Also, for missing activity (like the file write), please review the [wiki page](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Linux-with-Audit) for details on how to use the Audit reporter. You can use the saved audit log that is consumed by the Audit reporter as mentioned in the wiki page, and then confirm whether that activity is present in the saved audit log.
