### ISSUE TITLE
Collecting provenance on Windows with ProcMon

### ISSUE THREAD

**Issue by lizitong67** [ashish-gehani/SPADE#115]
I collected logs using the Process Monitor x64 in my WIN7, and I can only select the PML, CVS, and XML suffix when I try to save the logs.
I don't know how to save the logs with the .log suffix, and I don't know how to set the ANSI encoding.

**Comment by hassaanirshad** [comment]
Please refer to the updated wiki [here](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Windows).
