### ISSUE TITLE
Some datasets from transparent computing cannot be processed successfully.

### ISSUE THREAD

**Issue by h-197** [ashish-gehani/SPADE#116]
Hi

I am trying to read provenance graphs from several DARPA TC5 datasets.  I found that SPADE can successfully read the graphs of the Cadet group (https://drive.google.com/drive/folders/1YOaC0SMGjBnrT9952EwmKKngQkBYf4hY). However, it seems to miss many vertices and edges in the graphs from other groups (e.g., clearscope). According to the logs and source code, I found that the reason seems to be that SPADE does not handle the object types "IPC_OBJECT_SOCKET_UNNAMED" and "IPC_OBJECT_SOCKET_NETLINK". Could I configure SPADE to handle such objects and get the complete graph? Thank you very much!

**Comment by ashish-gehani** [comment]
SPADE's CDM Reporter is designed to ingest data generated by SPADE's CDM Storage, not data from other TC systems. For a list of events emitted by the CDM Storage, see: https://github.com/ashish-gehani/SPADE/wiki/System-calls-underlying-CDM-events
