### ISSUE TITLE
Couldn't view provenance in a graph database

### ISSUE THREAD

**Issue by bu-shuo** [ashish-gehani/SPADE#120]
`bin/neo4j start`  yields errors

### neo4j.log:
`Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint`
`Caused by: java.lang.ClassNotFoundException: org.neo4j.server.CommunityEntryPoint`

### java version:
java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)

**Comment by hassaanirshad** [comment]
On Ubuntu 18, according to requirements mentioned [here](https://github.com/ashish-gehani/SPADE/wiki/Requirements), `bin/neo4j start` doesn't result in an error.

Searching online for the error shared by you, the following Neo4j issue is found that might be of help to you: (https://github.com/neo4j/neo4j/issues/11965).

Hope that helps.
