### ISSUE TITLE
Exception caused by versionAnnotation 

### ISSUE THREAD

**Issue by ahmadzuhd** [ashish-gehani/SPADE#122]
I think the version annotation should be changed to version (small v) instead of capital v. I got the below exception when using the CycleAvoidance Filter:

spade.core.Kernel$1 run SEVERE: Error registering Main Thread
java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:614)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at spade.filter.CycleAvoidance.putEdge(CycleAvoidance.java:80)
        at spade.core.AbstractFilter.putInNextFilter(AbstractFilter.java:78)
        at spade.filter.CrossNamespaces.putEdge(CrossNamespaces.java:100)
        at spade.core.Kernel$1.run(Kernel.java:511)
        at java.base/java.lang.Thread.run(Thread.java:829)

https://github.com/ashish-gehani/SPADE/blob/80c3028905eff95f6b1893fd0ac46fe2f3994249/src/spade/filter/CycleAvoidance.java#L41

**Comment by hassaanirshad** [comment]
Thank you for reporting the issue. This solution to this issue is under development, and will take a while.

You might want to take a look at the filter [GraphFinesse](https://github.com/ashish-gehani/SPADE/wiki/Available-filters#graphfinesse) which has been updated just now.

Issue is being kept open until `CycleAvoidance` issue is resolved.

**Comment by hassaanirshad** [comment]
Thank you for your patience.

The `CycleAvoidance` filter has been updated to resolve the reported issue. Please see the updated wiki [here](https://github.com/ashish-gehani/SPADE/wiki/Available-filters#cycleavoidance).

Another filter [VersionOnWrite](https://github.com/ashish-gehani/SPADE/wiki/Available-filters#versiononwrite) has been added to remove cycles from a provenance graph. 

Details of different approaches for removing cycles in `GraphFinesse`, `CycleAvoidance`, and `VersionOnWrite` can be found [here](https://www.usenix.org/legacy/event/fast09/tech/slides/muniswamy.pdf).
