### ISSUE TITLE
issues about audit log output

### ISSUE THREAD

**Issue by F14me7wq** [ashish-gehani/SPADE#123]
error like this：
-> add reporter Audit outputLog=/tmp/audit.log
Adding reporter Audit... failed

I don't know why failed?

**Comment by hassaanirshad** [comment]
Please review the information [here](https://github.com/ashish-gehani/SPADE/wiki/Interaction) to help resolve, or report an issue.

More information about `Audit` reporter usage can be found [here](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Linux-with-Audit).

Closing this issue. Please open a new issue with the error that cannot be resolved.
