### ISSUE TITLE
Unable to set fileIO

### ISSUE THREAD

**Issue by Miakcmy** [ashish-gehani/SPADE#125]
I have created an Audit in Ubuntu 18. However, when I set 'add reporter Audit fileIO=true', it reported errors,and here are the mainly logs. What should I do? Thanks!!

`
2月 11, 2023 3:12:24 **上午** spade.reporter.audit.artifact.ArtifactManager <init> 严重: Failed to create external map 'AuditArtifactsMap' from arguments: ExternalMapArgument [mapId=AuditArtifactsMap, screenArgument=CreateFromArgs [expectedElements=1000000, falsePositiveProbability=1.0E-6, savePath=null, name=BloomFilter], cacheArgument=LRUCacheArgument [size=100000, name=LRU], storeArgument=StoreArgument [name=BerkeleyDB, argument=BerkeleyDBArgument [environmentPath=tmp/externalMap/berkeleyDb/reporter/audit/AritfactsMap, dbName=AuditArtifactsMapDb, deleteOnClose=true], reportingArgument=null], reportingIntervalMillis=120000, flushCacheOnClose=false]
2月 11, 2023 3:12:24 上午 spade.reporter.audit.artifact.ArtifactManager <init> 严重: Failed to create store
Database open failed
Database already opened

2月 11, 2023 3:12:24 上午 spade.reporter.Audit _launch 严重: Failed to instantiate artifact manager
java.lang.Exception: Failed to create external map
	at spade.reporter.audit.artifact.ArtifactManager.<init>(ArtifactManager.java:344)
	at spade.reporter.Audit._launch(Audit.java:373)
	at spade.reporter.Audit.launch(Audit.java:278)
	at spade.core.Kernel.addReporterCommand(Kernel.java:948)
	at spade.core.Kernel.addCommand(Kernel.java:1111)
	at spade.core.Kernel.executeCommand(Kernel.java:621)
	at spade.core.Kernel$LocalControlConnection.run(Kernel.java:1978)
	at java.base/java.lang.Thread.run(Thread.java:829)

2月 11, 2023 3:12:24 上午 spade.reporter.Audit launch 严重: Failed to launch reporter
2月 11, 2023 3:12:24 上午 spade.core.Kernel addReporterCommand 严重: Unable to launch reporter
`

**Comment by ashish-gehani** [comment]
The issue appears to be in your setup / environment.

Attached is a [Vagrantfile](https://developer.hashicorp.com/vagrant/tutorials/getting-started/getting-started-index) where `add reporter Audit fileIO=true` works on Ubuntu 18.04.

[Vagrantfile.zip](https://github.com/ashish-gehani/SPADE/files/10712106/Vagrantfile.zip)
