### ISSUE TITLE
removing vertices with operator "-" does not work as expected 

### ISSUE THREAD

**Issue by iai-rsa** [ashish-gehani/SPADE#126]
The following example extracted from the referenced paper (http://www.csl.sri.com/users/gehani/papers/Queue-2021.QuickGrail.pdf)
 $privilege_escalated = $chameleons - $chameleons.getVertex(uid != 0) 
does not work as expected.

Although it does remove some vertices according to the constraint, it does not remove the corresponding edges. As a result, it does not really make the graph more readable.

**Comment by ashish-gehani** [comment]
Perhaps you want to use getSubgraph() to find incident edges and subtract them out, too?
