### ISSUE TITLE
Unknown data format in postgreSQL

### ISSUE THREAD

**Issue by polosec** [ashish-gehani/SPADE#130]
I use postgresql to store data,but why the data format is different from document?
<img width="767" alt="image" src="https://github.com/ashish-gehani/SPADE/assets/34666152/b4abd994-fc67-46d7-b741-3097cda1795d">
I executed command in ssh: cat /etc/passwd , curl 1.1.1.1:1111 . but I can't find any relevant results from database.

**Comment by ashish-gehani** [comment]
These are the vertex hashes. See Section 4.2 of **Scaling SPADE to "Big Provenance"**, _8th USENIX Workshop on the Theory and Practice of Provenance (TaPP)_, 2016. [[PDF](http://www.csl.sri.com/users/gehani/papers/TaPP-2016.Scaling.pdf)]

**Comment by polosec** [comment]
hello,why I executed command curl google.com ,but no results can be found in database?
