### ISSUE TITLE
JSON storage sometimes fails

### ISSUE THREAD

**Issue by AndrewGrecu** [ashish-gehani/SPADE#131]
When setting up an audit reporter with a JSON storage, the data seems to be viewable in /tmp/provenance.json. However, after some time has passed, the file reverts back to being empty and ready to be written with just a singular [    . Im not sure if this is normal or not but it has become a problem when the file does not stay consistent.

**Comment by ashish-gehani** [comment]
Perhaps you can submit a [Vagrantfile](https://www.vagrantup.com) to reproduce this?

**Comment by AndrewGrecu** [comment]
[Vagrantfile.txt](https://github.com/ashish-gehani/SPADE/files/12152571/Vagrantfile.txt)
You have to remove the .txt. Regardless, Once SPADE is done setting up I just follow the wiki on how to first set up JSON storage with the default command and then add a simple audit reporter. Sometimes the file will have data and sometimes it won't.
