### ISSUE TITLE
Configuring SPADE to create JSON output as fast as possible

### ISSUE THREAD

**Issue by AndrewGrecu** [ashish-gehani/SPADE#132]
I was wondering on what settings to change to configure SPADE for the fastest output of JSON provenance. Currently, I have only changed the JSON storage config to :flushAfterBytes=10. I have also changed the audit reporter config to :reportingInterval=2. I was wondering if there were any other configurations so that the /tmp/provenance.json file is written to as fast as possible.
I am using an Audit reporter and JSON storage at /tmp/provenance.json.

**Comment by ashish-gehani** [comment]
_reportingInterval_ in the Audit Reporter configuration controls how often statistics are reported in the SPADE log.

If the Audit Reporter is used for "live" collection, the underlying Linux kernel's Audit configuration affects the latency of records arriving from the kernel, via _auditd_ and _audispd_. On Ubuntu you can adjust the backlog (in /etc/audit/audit.rules), when to flush (freq in /etc/audit/auditd.conf), and the queue depth (q_depth in  /etc/audisp/audispd.conf).

See the description of SPADE Kernel buffering in the [MW '12 paper](https://www.csl.sri.com/users/gehani/papers/MW-2012.SPADE.pdf), which can be controlled in [cfg/spade.core.BlockingBuffer.config](https://github.com/ashish-gehani/SPADE/blob/master/cfg/spade.core.BlockingBuffer.config).
