### ISSUE TITLE
SPADE storage and reporter deleting themselves

### ISSUE THREAD

**Issue by AndrewGrecu** [ashish-gehani/SPADE#133]
Currently, I am running SPADE on a virtual machine. Sometimes when the virtual machine is stopped and is started again, SPADE will have either gotten rid of either a reporter or a storage. This only occurs when the instance is turned off and back on. I am using a JSON storage and Audit reporter. The filter that I am using, however, will not delete its self and act normal.

**Comment by ashish-gehani** [comment]
When the SPADE Kernel is stopped, it saves its configuration (as visible in the control client) in `cfg/spade.client.Control.config`. If this file is populated when the Kernel starts, an attempt will be made to run each line. To check why some line(s) failed, you can look in the SPADE log.
