### ISSUE TITLE
Couldn't add reporter

### ISSUE THREAD

**Issue by chelun-c000** [ashish-gehani/SPADE#135]
I've read issue #113, but I still couldn't fix it. What should I do? Thank you! :)
I use Fedora 34. Everything is fine but I just couldn't add reporter Audit in control panel.
Here is the log:

11月 29, 2023 3:26:30 下午 spade.core.Kernel getHostName INFO: SPADE host name: 'fedora'
11月 29, 2023 3:30:41 下午 spade.core.Kernel addStorageCommand INFO: Adding storage: Neo4j
11月 29, 2023 3:30:41 下午 spade.screen.Deduplicate loadBloomFilterAndCache INFO: Vertex BloomFilter initialized from arguments: [falsePositiveProbability=0.000000100, expectedElements=1000000]
11月 29, 2023 3:30:41 下午 spade.screen.Deduplicate loadBloomFilterAndCache INFO: Vertex BloomFilter would NOT be saved on shutdown
11月 29, 2023 3:30:41 下午 spade.screen.Deduplicate loadBloomFilterAndCache INFO: Vertex cache created with max size '10000'
11月 29, 2023 3:30:41 下午 spade.screen.Deduplicate loadBloomFilterAndCache INFO: Edge BloomFilter initialized from arguments: [falsePositiveProbability=0.000000100, expectedElements=1000000]
11月 29, 2023 3:30:41 下午 spade.screen.Deduplicate loadBloomFilterAndCache INFO: Edge BloomFilter would NOT be saved on shutdown
11月 29, 2023 3:30:41 下午 spade.screen.Deduplicate loadBloomFilterAndCache INFO: Edge cache created with max size '10000'
11月 29, 2023 3:30:41 下午 spade.screen.Deduplicate printStats INFO: verticesBlocked=0, verticesNotBlocked=0, edgesBlocked=0, edgesNotBlocked=0
11月 29, 2023 3:30:41 下午 spade.core.AbstractScreen initializeScreen INFO: Successfully initialized screen [name:spade.screen.Deduplicate, arguments:]
11月 29, 2023 3:30:41 下午 spade.storage.Neo4j initialize INFO: Configuration: dbms.directories.neo4j_home=/home/cchelun/SPADE/lib/neo4j-community-4.1.1, database=spade.graph, dbms.default_database=neo4j, constructedDatabasePath=/home/cchelun/SPADE/lib/neo4j-community-4.1.1/spade.graph/databases/neo4j, neo4jConfigFilePath=/home/cchelun/SPADE/cfg/neo4j.properties, vertexCacheMode=NODE, edgeCacheFindMode=NONE, flushBufferSize=25000, flushAfterSeconds=60, bufferLimit=100000 (buffering:enabled), transactionTimeoutInSeconds=300 (limited:yes), forceShutdown=false, reset=false, maxRetries=10, waitForIndexSeconds=10, hashKeyCollisionAction=DISCARD, hashPropertyName=hash, edgeSymbolsPropertyName=spade_edge_symbols, nodePrimaryLabel=VERTEX (VERTEX), edgeRelationshipType=EDGE (EDGE), querySymbolsNodeLabel=spade_query_symbols (spade_query_symbols), index.vertex=ALL, index.edge=ALL, indexNamePrefix=spade_index_, reportingIntervalSeconds=120 (enabled), debug=false, timeMe=true, sleepWaitMillis=10, mainThreadSleepWaitMillis=0, test=false, test.vertex.total=0, test.edge.degree=0, test.vertex.annotations=[], test.edge.annotations=[], Ignored unexpected argument(s)={screen=Deduplicate}
11月 29, 2023 3:30:43 下午 spade.storage.Neo4j initialize INFO: Database absolute path: /home/cchelun/SPADE/lib/neo4j-community-4.1.1/spade.graph/databases/neo4j
11月 29, 2023 3:30:44 下午 spade.core.Kernel addStorageCommand INFO: Storage added: class spade.storage.Neo4j database=spade.graph. Using screens: [Deduplicate]
11月 29, 2023 3:30:59 下午 spade.core.Kernel removeStorageCommand INFO: Shutting down storage: Neo4j
11月 29, 2023 3:30:59 下午 spade.screen.Deduplicate printStats INFO: verticesBlocked=0, verticesNotBlocked=0, edgesBlocked=0, edgesNotBlocked=0
11月 29, 2023 3:30:59 下午 spade.core.AbstractScreen shutdownScreen INFO: Successfull screen shutdown for 'Deduplicate'
11月 29, 2023 3:30:59 下午 spade.storage.Neo4j shutdown INFO: Shutdown called. Waiting for 0 pending task(s) to complete
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Storage STATS Start [interval=1]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Vertices. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Vertex Cache Miss. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Vertex Cache Hit. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Vertex DB Hit. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Edges. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Edge Cache Miss. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Edge Cache Hit. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Edge DB Hit. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Pending Tasks Incoming. Rate per minute [Overall=23.707; Interval=23.707]. Absolute [Overall=7, Interval=7]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Pending Tasks Outgoing. Rate per minute [Overall=23.707; Interval=23.707]. Absolute [Overall=7, Interval=7]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: JVM Heap Size In Use: 0.193 GB
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Storage STATS End [interval=1]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Storage action timer: key=EXECUTE-TaskExecuteQuery, count=7, sum=0.120 seconds, avg=0.017143 seconds
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Storage action timer: key=TX-COMMIT, count=15, sum=0.000 seconds, avg=0.000000 seconds
11月 29, 2023 3:30:59 下午 spade.storage.Neo4j$1 run INFO: Exited main DB task executor thread
11月 29, 2023 3:30:59 下午 spade.storage.Neo4j shutdown INFO: Pending tasks going to be discarded: '0'. Continuing with shutdown ...
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Storage STATS Start [interval=2]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Vertices. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Vertex Cache Miss. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Vertex Cache Hit. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Vertex DB Hit. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Edges. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Edge Cache Miss. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Edge Cache Hit. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Edge DB Hit. Rate per minute [Overall=0.000; Interval=0.000]. Absolute [Overall=0, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Pending Tasks Incoming. Rate per minute [Overall=23.453; Interval=0.000]. Absolute [Overall=7, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Pending Tasks Outgoing. Rate per minute [Overall=23.453; Interval=0.000]. Absolute [Overall=7, Interval=0]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: JVM Heap Size In Use: 0.220 GB
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Storage STATS End [interval=2]
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Storage action timer: key=EXECUTE-TaskExecuteQuery, count=7, sum=0.120 seconds, avg=0.017143 seconds
11月 29, 2023 3:30:59 下午 spade.storage.neo4j.StorageStats print INFO: Storage action timer: key=TX-COMMIT, count=15, sum=0.000 seconds, avg=0.000000 seconds
11月 29, 2023 3:30:59 下午 spade.core.Kernel removeStorageCommand INFO: Storage shut down: Neo4j (0 vertices and 0 edges were added)
11月 29, 2023 3:41:01 下午 spade.core.Kernel addReporterCommand INFO: Adding reporter: Audit
11月 29, 2023 3:41:01 下午 spade.core.BlockingBuffer log INFO: [Audit] workableFreeMemory=20.000%, reportingIntervalSeconds=120(enabled), sleepWaitMillis=1000
11月 29, 2023 3:41:01 下午 spade.core.Kernel addReporterCommand INFO: Memory usage limited buffer used for reporter 'Audit' with 'workableFreeMemory'='20' from '/home/cchelun/SPADE/./cfg/spade.core.AbstractReporter.config'
11月 29, 2023 3:41:01 下午 spade.reporter.Audit _launch INFO: Intervaler [isEnabled=true, intervalTimeMillis=120000]
11月 29, 2023 3:41:01 下午 spade.reporter.Audit _launch INFO: OutputLog [enabled=false, outputLogPath=null, rotationEnabled=false, rotateLogAfterLines=0]
11月 29, 2023 3:41:01 下午 spade.reporter.Audit _launch INFO: LinuxConstants [configFilePath=/home/cchelun/SPADE/./cfg/spade.reporter.audit.LinuxConstants.config]
11月 29, 2023 3:41:01 下午 spade.reporter.Audit _launch INFO: Input [spadeAuditBridgePath=/home/cchelun/SPADE/./bin/spadeAuditBridge, spadeAuditBridgeName=spadeAuditBridge, mode=LIVE, linuxAuditSocketPath=/var/run/audispd_events, inputLog=null, inputLogRotate=false, inputLogList=null, inputLogListFile=null, inputDir=null, inputDirTime=null, waitForLog=false]
11月 29, 2023 3:41:01 下午 spade.reporter.Audit _launch INFO: ProcessUserSyscallFilter [systemCallRuleType=DEFAULT, userName=cchelun, userId=1000, userMode=IGNORE, namesOfProcessesToIgnore=[kauditd, audispd, auditd], namesOfParentProcessesToIgnore=[kauditd, audispd, auditd]]
11月 29, 2023 3:41:01 下午 spade.reporter.Audit _launch INFO: KernelModuleConfiguration [kernelModuleMain=null, kernelModuleController=null, harden=false, localEndpoints=false, handleLocalEndpoints=false, hardenProcesses=[], networkAddressTranslation=false, handleNetworkAddressTranslation=false, netfilterHooksLogCT=false, netfilterHooksUser=false]
11月 29, 2023 3:41:01 下午 spade.reporter.Audit _launch INFO: ArtifactConfiguration [unixSockets=false, versionNetworkSockets=false, versionFiles=true, versionMemorys=true, versionNamedPipes=true, versionUnnamedPipes=true, versionUnknowns=true, versionUnixSockets=true, versionUnixSocketPairs=true, versionNetworkSocketPairs=false, versionSysVMessageQueue=true, versionSysVSharedMemory=true, versionPosixMessageQueue=true, versions=true, epochs=true, permissions=true, keepingArtifactPropertiesMap=true]
11月 29, 2023 3:41:01 下午 spade.reporter.Audit _launch INFO: AuditConfiguration [agents=false, anonymousMmap=true, control=true, cwd=true, excludeProctitle=true, failfast=true, fileIO=false, fsids=false, inode=false, IPC=false, memorySyscalls=true, mergeUnit=0, namespaces=false, netIO=false, reportKill=true, rootFS=true, simplify=true, simpleCreds=true, units=false]
11月 29, 2023 3:41:01 下午 spade.reporter.audit.artifact.ArtifactManager <init> INFO: AuditArtifactsMap: ExternalMapArgument [mapId=AuditArtifactsMap, screenArgument=CreateFromArgs [expectedElements=1000000, falsePositiveProbability=1.0E-6, savePath=null, name=BloomFilter], cacheArgument=LRUCacheArgument [size=100000, name=LRU], storeArgument=StoreArgument [name=BerkeleyDB, argument=BerkeleyDBArgument [environmentPath=tmp/externalMap/berkeleyDb/reporter/audit/AritfactsMap, dbName=AuditArtifactsMapDb, deleteOnClose=true], reportingArgument=null], reportingIntervalMillis=120000, flushCacheOnClose=false]
11月 29, 2023 3:41:01 下午 spade.reporter.audit.process.ProcessManager <init> INFO: AuditProcessesMap: ExternalMapArgument [mapId=AuditProcessesMap, screenArgument=CreateFromArgs [expectedElements=1000000, falsePositiveProbability=1.0E-6, savePath=null, name=BloomFilter], cacheArgument=LRUCacheArgument [size=66000, name=LRU], storeArgument=StoreArgument [name=BerkeleyDB, argument=BerkeleyDBArgument [environmentPath=tmp/externalMap/berkeleyDb/reporter/audit/ProcessesMap, dbName=AuditProcessesMapDb, deleteOnClose=true], reportingArgument=null], reportingIntervalMillis=120000, flushCacheOnClose=false]
11月 29, 2023 3:41:01 下午 spade.reporter.Audit _launch INFO: Launched SPADE audit bridge process with pid '7173' using command: /home/cchelun/SPADE/./bin/spadeAuditBridge  -s /var/run/audispd_events
11月 29, 2023 3:41:01 下午 spade.reporter.Audit$6 accept INFO: Successfully deleted all existing rules
11月 29, 2023 3:41:01 下午 spade.reporter.Audit _launch SEVERE: Failed to setup Linux audit rules
java.lang.Exception: Failed to set audit rules
	at spade.reporter.audit.AuditControlManager.set(AuditControlManager.java:296)
	at spade.reporter.Audit._launch(Audit.java:506)
	at spade.reporter.Audit.launch(Audit.java:278)
	at spade.core.Kernel.addReporterCommand(Kernel.java:948)
	at spade.core.Kernel.addCommand(Kernel.java:1111)
	at spade.core.Kernel.executeCommand(Kernel.java:621)
	at spade.core.Kernel$LocalControlConnection.run(Kernel.java:1978)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.Exception: Failed to add audit rule
	at spade.reporter.audit.AuditControlManager.appendRule(AuditControlManager.java:235)
	at spade.reporter.audit.AuditControlManager.set(AuditControlManager.java:284)
	... 7 more
Caused by: java.lang.Exception: Failed to execute auditctl command: 'auditctl -a exit,always -F arch=b64 -F uid!=1000 -S bind -S accept -S accept4 -S socket -S mmap -S mprotect -S madvise -S unlink -S unlinkat -S link -S linkat -S symlink -S symlinkat -S clone -S fork -S vfork -S execve -S open -S openat -S creat -S close -S mknod -S mknodat -S dup -S dup2 -S dup3 -S fcntl -S rename -S renameat -S setuid -S setreuid -S setresuid -S setgid -S setregid -S setresgid -S chmod -S fchmod -S fchmodat -S truncate -S ftruncate -S pipe -S pipe2 -S tee -S splice -S vmsplice -S socketpair -S init_module -S finit_module -S ptrace -S chdir -S fchdir -S chroot -S pivot_root -F success=1 -F pid!=4838 -F pid!=6841 -F pid!=7173 -F ppid!=4838 -F ppid!=6841 -F ppid!=7173'
	at spade.reporter.audit.AuditControlManager.executeAuditctl(AuditControlManager.java:203)
	at spade.reporter.audit.AuditControlManager.appendRule(AuditControlManager.java:233)
	... 8 more
Caused by: java.lang.Exception: Error: [Syscall name unknown: unlink]
	at spade.reporter.audit.AuditControlManager.executeAuditctl(AuditControlManager.java:199)
	... 9 more

11月 29, 2023 3:41:01 下午 spade.reporter.Audit launch SEVERE: Failed to launch reporter
11月 29, 2023 3:41:01 下午 spade.reporter.Audit$4 accept INFO: [SPADE audit bridge] [OUTPUT] Exiting error thread
11月 29, 2023 3:41:01 下午 spade.reporter.audit.AuditEventReader printStats INFO: Overall rate: 0 records/sec in 0.068 seconds. Interval rate: 0 records/sec in 0.068 seconds.
11月 29, 2023 3:41:01 下午 spade.reporter.audit.AuditEventReader printStats INFO: Overall rate: 0 records/sec in 0.067 seconds. Interval rate: 0 records/sec in 0.067 seconds.
11月 29, 2023 3:41:01 下午 spade.utility.map.external.ExternalMap printStats INFO: AuditArtifactsMap: evictions=0, falsePositives=0, cacheHits=0, cacheMisses=0, screenCount=0, cacheCount=0, storeSize=(21 KB)
11月 29, 2023 3:41:01 下午 spade.utility.map.external.ExternalMap printStats INFO: AuditProcessesMap: evictions=0, falsePositives=0, cacheHits=0, cacheMisses=0, screenCount=0, cacheCount=0, storeSize=(21 KB)
11月 29, 2023 3:41:01 下午 spade.core.Kernel addReporterCommand SEVERE: Unable to launch reporter
11月 29, 2023 3:41:01 下午 spade.reporter.audit.AuditEventReader printStats INFO: Overall rate: 0 records/sec in 0.165 seconds. Interval rate: 0 records/sec in 0.165 seconds.
11月 29, 2023 3:41:01 下午 spade.reporter.Audit$1 run INFO: Exiting event reader thread for SPADE audit bridge

**Comment by ashish-gehani** [comment]
See:
`Caused by: java.lang.Exception: Failed to execute auditctl command: 'auditctl -a exit,always -F arch=b64 -F uid!=1000 -S bind -S accept -S accept4 -S socket -S mmap -S mprotect -S madvise -S unlink -S unlinkat -S link -S linkat -S symlink -S symlinkat -S clone -S fork -S vfork -S execve -S open -S openat -S creat -S close -S mknod -S mknodat -S dup -S dup2 -S dup3 -S fcntl -S rename -S renameat -S setuid -S setreuid -S setresuid -S setgid -S setregid -S setresgid -S chmod -S fchmod -S fchmodat -S truncate -S ftruncate -S pipe -S pipe2 -S tee -S splice -S vmsplice -S socketpair -S init_module -S finit_module -S ptrace -S chdir -S fchdir -S chroot -S pivot_root -F success=1 -F pid!=4838 -F pid!=6841 -F pid!=7173 -F ppid!=4838 -F ppid!=6841 -F ppid!=7173'
at spade.reporter.audit.AuditControlManager.executeAuditctl(AuditControlManager.java:203)
at spade.reporter.audit.AuditControlManager.appendRule(AuditControlManager.java:233)
... 8 more
Caused by: java.lang.Exception: Error: [Syscall name unknown: unlink]`

and: https://man7.org/linux/man-pages/man8/auditctl.8.html

This is not a SPADE issue. Debug the error on the underlying system.
