### ISSUE TITLE
spade control & spade debug don't work

### ISSUE THREAD

**Issue by MagdyNasr41** [ashish-gehani/SPADE#137]
spade start results to this output:
nohup: redirecting stderr to stdout
Running SPADE with PID = 2702

Which I think works properly but spade control prints: Unable to set up remote secure communication streams! java.net.ConnectException: Connection refused (Connection refused)

and spade debug prints: 
![image](https://github.com/ashish-gehani/SPADE/assets/90320433/25c4f4c0-8fdd-453f-bfbe-0fe5afbf1f80)

which I think a memory dependant error.

## Hence I've read the previous similar closed issues here:
https://github.com/ashish-gehani/SPADE/issues/85
which didn't provide any solution to the problem of spade control
and here: https://github.com/ashish-gehani/SPADE/issues/124
Which made me check spade status but it prints "Running" that i think a result that shows that everything is fine!

## Here are the detailed steps  I followed from the begining, each command and its result "I wrote the last line for huge results":
1-Downloaded Ububtu 18.04.6 LTS

2-magdynasr@ENG-MEGZAWY:~$ sudo add-apt-repository -y ppa:openjdk-r/ppa
result: Reading package lists... Done

3-magdynasr@ENG-MEGZAWY:~$ sudo apt-get update
result: Reading package lists... Done

4-magdynasr@ENG-MEGZAWY:~$ sudo apt-get install -y openjdk-11-jdk
result is huge so I am not reporting it

5-magdynasr@ENG-MEGZAWY:~$ sudo apt-get install -y auditd bison clang cmake curl flex fuse git ifupdown libaudit-dev libfuse-dev linux-headers-`uname -r` lsof pkg-config unzip uthash-dev wget
result: 
se-dev linux-headers-`uname -r` lsof pkg-config unzip uthash-dev wget
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-5.15.133.1-microsoft-standard-WSL2
E: Couldn't find any package by glob 'linux-headers-5.15.133.1-microsoft-standard-WSL2'
E: Couldn't find any package by regex 'linux-headers-5.15.133.1-microsoft-standard-WSL2'

6-magdynasr@ENG-MEGZAWY:~$ git clone https://github.com/ashish-gehani/SPADE.git
result: Resolving deltas: 100% (12011/12011), done.

7-magdynasr@ENG-MEGZAWY:~/SPADE$ ./configure
Result: 
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/home/magdynasr/SPADE':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

8-So I downloaded the gcc compiler: 
magdynasr@ENG-MEGZAWY:~$ sudo apt update
magdynasr@ENG-MEGZAWY:~$ sudo apt install build-essential

9-magdynasr@ENG-MEGZAWY:~/SPADE$ ./configure

10-magdynasr@ENG-MEGZAWY:~/SPADE$ make

11-magdynasr@ENG-MEGZAWY:~/SPADE/bin$ spade start
nohup: redirecting stderr to stdout
Running SPADE with PID = 2702

12-magdynasr@ENG-MEGZAWY:~/SPADE/bin$ spade debug
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000429990000, 7892041728, 0) failed; error='Not enough space' (errno=12)

There is insufficient memory for the Java Runtime Environment to continue.
Native memory allocation (mmap) failed to map 7892041728 bytes for committing reserved memory.
An error report file with more information is saved as:
/home/magdynasr/SPADE/hs_err_pid2810.log

13-magdynasr@ENG-MEGZAWY:~/SPADE/bin$ spade control
Unable to set up remote secure communication streams! java.net.ConnectException: Connection refused (Connection refused)

**Comment by ashish-gehani** [comment]
The (virtual?) machine does not have sufficient memory.
