### ISSUE TITLE
SPADE doesn't perform well on Virtual Box

### ISSUE THREAD

**Issue by TomMD** [ashish-gehani/SPADE#14]
When used on virtual box, Linux audit infrastructure misses events (even when set to lossless, evidently a known issue in some circles).   Thus, SPADE on VirtualBox is not a good setup for getting complete traces.  This fact should probably be documented somewhere.

**Comment by ashish-gehani** [comment]
This is not an issue with SPADE. It is an issue with Linux Audit on VirtualBox.

It can be reported upstream on the Audit mailing list.

**Comment by TomMD** [comment]
I know it isn't a bug that SPADE directly is responsible for. Regardless of the root cause, unless SPADE has an alternative backend it seems prudent to warn users.  No?
