### ISSUE TITLE
the namespace process in kernel_modules only grasps processes with syscall 56

### ISSUE THREAD

**Issue by KSGJ-CLOUD** [ashish-gehani/SPADE#142]
Hello, the namespace process in kernel_modules only grasps processes with syscall 56. Why? Some processes without a namespace are mistakenly labeled as having a namespace, why?
![image](https://github.com/ashish-gehani/SPADE/assets/71766358/21fa7681-4e53-41f8-bab7-1b1e20547455)

**Comment by ashish-gehani** [comment]
You can consult the [source](https://github.com/ashish-gehani/SPADE/blob/master/src/spade/reporter/audit/kernel-modules/netio.c) and contact contributor @hassaanirshad .
