### ISSUE TITLE
When SPADE is running, Neo4j can't start

### ISSUE THREAD

**Issue by xiaqintangsong** [ashish-gehani/SPADE#145]
According to the wiki, I used Neo4j to store Linux Audit records.
But when SPADE is running, Neo4j can't start. When I start Neo4j, I have to stop SPADE first. So I can't see real-time Audit records in Neo4j webpage.
Is there any way to make Neo4j can display record changes in real time?
Thank you!

**Comment by ashish-gehani** [comment]
SPADE uses Neo4j as an embedded database.
