### ISSUE TITLE
Spade Namespace Filter

### ISSUE THREAD

**Issue by shumuchen** [ashish-gehani/SPADE#149]
I want to know if Namespace filter won't work when the reporter's input is JSON

**Comment by ashish-gehani** [comment]
If you are referring to the [CrossNamespaces Filter](https://github.com/ashish-gehani/SPADE/wiki/Available-filters#crossnamespaces) (used in the [PACED paper](https://www.csl.sri.com/users/gehani/papers/IC2E-2022.PACED.pdf)), the [default configuration](https://github.com/ashish-gehani/SPADE/blob/master/cfg/spade.filter.CrossNamespaces.config) is intended for use with the [Audit Reporter configured with namespace reporting](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Linux-with-Audit#configuring-namespace-reporting).

[1] PACED: Provenance-based Automated Container Escape Detection, 10th IEEE International Conference on Cloud Engineering (IC2E), 2022.

**Comment by shumuchen** [comment]
when i use aduit  Reporter with namespace reporting ,it works and I save the audit log output. 
I wanna use the log as audit reporter input (like `add filter CrossNamespaces position=1``add reporter Audit inputLog=input/audit.log`) to get the same crossnamespace-event json But it doesn't work.
Does this mean that filter can only work on real-time running systems?

**Comment by shumuchen** [comment]
> when i use aduit Reporter with namespace reporting ,it works and I save the audit log output. I wanna use the log as audit reporter input (like `` add filter CrossNamespaces position=1``add reporter Audit inputLog=input/audit.log ``) to get the same crossnamespace-event json But it doesn't work. Does this mean that filter can only work on real-time running systems?

`add reporter Audit inputLog=input/audit.log localEndpoints=true namespaces=true IPC=true networkAddressTranslation=true ` doesn't take effect either
