### ISSUE TITLE
How to collect log file events

### ISSUE THREAD

**Issue by neel** [ashish-gehani/SPADE#152]
I want to collect events from log files, such as access.log, error.log from nginx server. I first tried to collect it through auditd. But spade is overwriting the audit rules when it starts.

```bash
~/SPADE$ sudo systemctl restart auditd
~/SPADE$ sudo auditctl -l
-w /var/log/nginx/access.log -p rwxa -k nginx_access
-w /var/log/nginx/error.log -p rwxa -k nginx_error
```

After I start spade

```bash
~/SPADE$ ./bin/spade start
nohup: redirecting stderr to stdout
Running SPADE with PID = 1905
~/SPADE$ sudo auditctl -l
-a always,exit -F arch=b64 -S open,close,mmap,mprotect,pipe,madvise,dup,dup2,socket,accept,bind,socketpair,clone,fork,vfork,execve,fcntl,truncate,ftruncate,chdir,fchdir,rename,creat,link,unlink,symlink,chmod,fchmod,ptrace,setuid,setgid,setreuid,setregid,setresuid,setresgid,mknod,pivot_root,chroot,init_module,openat,mknodat,unlinkat,renameat,linkat,symlinkat,fchmodat,splice,tee,vmsplice,accept4,dup3,pipe2,finit_module -F uid!=1000 -F success=1 -F pid!=1951 -F pid!=1773 -F pid!=1905 -F pid!=31 -F ppid!=1951 -F ppid!=1773 -F ppid!=1905 -F ppid!=31
-a always,exit -F arch=b64 -S connect,exit,kill,exit_group -F uid!=1000 -F pid!=1951 -F pid!=1773 -F pid!=1905 -F pid!=31 -F ppid!=1951 -F ppid!=1773 -F ppid!=1905 -F ppid!=31
~/SPADE$ ./bin/spade stop
SPADE will stop after buffers clear
~/SPADE$ sudo auditctl -l
No rules
```

In `SPADE/log/SPADE_....log` I have

```
Oct 25, 2024 11:36:11 AM spade.reporter.audit.process.ProcessManager <init> INFO: AuditProcessesMap: ExternalMapArgument [mapId=AuditProcessesMap, screenArgument=CreateFromArgs [expectedElements=1000000, falsePositiveProbability=1.0E-6, savePath=null, name=BloomFilter], cacheArgument=LRUCacheArgument [size=66000, name=LRU], storeArgument=StoreArgument [name=BerkeleyDB, argument=BerkeleyDBArgument [environmentPath=tmp/externalMap/berkeleyDb/reporter/audit/ProcessesMap, dbName=AuditProcessesMapDb, deleteOnClose=true], reportingArgument=null], reportingIntervalMillis=120000, flushCacheOnClose=false]
Oct 25, 2024 11:36:11 AM spade.reporter.Audit _launch INFO: Launched SPADE audit bridge process with pid '3123' using command: /home/user/SPADE/./bin/spadeAuditBridge  -s /var/run/audispd_events
Oct 25, 2024 11:36:11 AM spade.reporter.Audit$6 accept INFO: Successfully deleted all existing rules
Oct 25, 2024 11:36:11 AM spade.reporter.Audit$6 accept INFO: Successfully added audit rule: 'exit,always -F arch=b64 -F uid!=1000 -S bind -S accept -S accept4 -S socket -S mmap -S mprotect -S madvise -S unlink -S unlinkat -S link -S linkat -S symlink -S symlinkat -S clone -S fork -S vfork -S execve -S open -S openat -S creat -S close -S mknod -S mknodat -S dup -S dup2 -S dup3 -S fcntl -S rename -S renameat -S setuid -S setreuid -S setresuid -S setgid -S setregid -S setresgid -S chmod -S fchmod -S fchmodat -S truncate -S ftruncate -S pipe -S pipe2 -S tee -S splice -S vmsplice -S socketpair -S init_module -S finit_module -S ptrace -S chdir -S fchdir -S chroot -S pivot_root -F success=1 -F pid!=1773 -F pid!=3123 -F pid!=3076 -F pid!=31 -F ppid!=1773 -F ppid!=3123 -F ppid!=3076 -F ppid!=31'
Oct 25, 2024 11:36:11 AM spade.reporter.Audit$6 accept INFO: Successfully added audit rule: 'exit,always -F arch=b64 -F uid!=1000 -S exit -S exit_group -S connect -S kill -F pid!=1773 -F pid!=3123 -F pid!=3076 -F pid!=31 -F ppid!=1773 -F ppid!=3123 -F ppid!=3076 -F ppid!=31'
Oct 25, 2024 11:36:11 AM spade.reporter.Audit launch INFO: Successfully launched reporter
Oct 25, 2024 11:36:11 AM spade.core.Kernel addReporterCommand INFO: Reporter added: Audit 
```

So, the question is, is there any SPADE specific way to capture events from log files and include that into provenance graph? or I have to rely only on auditd ? If its auditd only then how to make the log file watching rule persist instead of being overwritten by SPADE?

**Comment by ashish-gehani** [comment]
SPADE's Audit Reporter selects the rules needed to support the options configured, as described in the Wiki [here](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Linux-with-Audit). More granular settings are in the Audit Reporter's configuration file [here](https://github.com/ashish-gehani/SPADE/blob/master/cfg/spade.reporter.Audit.config). It does not support arbitrary user-specified Audit rules.

**Comment by neel** [comment]
Thanks for your reply. 

> It does not support arbitrary user-specified Audit rules.

But does it support monitoring for the specific log files e.g. nginx logs, postgresql logs etc.. ? What do I need to do in order to collect information from any log file (other than dumping write syscalls) ?

In the configuration file there is a property `inputLog`. Should I add paths to multiple log files separated by space there ? 

```ini
# Path to input log file. If not specified then reporter run in LIVE mode
#inputLog = /var/log/nginx/access.log /var/log/nginx/error.log
```

**Comment by ashish-gehani** [comment]
As described [here](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Linux-with-Audit#using-a-saved-log): 

> Instead of collecting Linux Audit records from the running system, a previously saved log can be used by specifying it with the inputLog argument.

`inputLog` cannot be used for arbitrary logs.

**Comment by neel** [comment]
Okay so inputLog doesn't serve the purpose of monitoring any log files. 
Also, adding custom rules to monitor a log file through auditd will not work as you have mention.

But, I want to monitor log files. Not any arbitrary log files, but very specific ones, like  `/var/log/nginx/access.log` and `/var/log/nginx/error.log`. Is that possible with SPADE ?
