### ISSUE TITLE
Getting fd and args from SYSCALL audit log

### ISSUE THREAD

**Issue by neel** [ashish-gehani/SPADE#154]
From the audit log I can get the `path` for the corresponding `syscall`s such as `create`/`open`/`close` etc.. But I also want to store the `fd` and the `args` in the storage too, just as another key value pair. I was checking the source code. It didn't look like the audit reporter is skipping the `a0`, `a1` ... or `exit` keys while parsing the syscall. But I don't see those items in my storage. So, these keys must have been lost somewhere. Can I get/put them back ?

**Comment by ashish-gehani** [comment]
The data model and schema of the Audit Reporter is described [here](https://github.com/ashish-gehani/SPADE/wiki/Audit-provenance). Only a subset of the Audit log is lifted into the provenance representation, as explained here: **TRACE: Enterprise-Wide Provenance Tracking For Real-Time APT Detection**, _IEEE Transactions on Information Forensics and Security (TIFS)_, 2021. [[PDF]](http://www.csl.sri.com/users/gehani/papers/TIFS-2021.TRACE.pdf)

**Comment by neel** [comment]
According to the data model refered, fd is lifted only for subtype unknown.

But I have forked the project and in my forked version I want to lift fd in all cases.

I am looking for the part of the code which is responsible for excluding fd, or including only a specific set of attributes. So that I can tweak that part in order to achieve the desired functionality.

**Comment by ashish-gehani** [comment]
This is not well-defined. There is NOT a one-to-one relationship between system calls and provenance graph edges.

Provenance is inferred from Audit records. However, this a stateful process. See the `Related Work -> Provenance Frameworks -> Whole system` section of the TRACE paper referenced above, for example. Consequently, an emitted edge is a function of the effects of past system calls (as seen at the end [here](https://github.com/ashish-gehani/SPADE/wiki/Linux-Audit-System-Call-Events)), the Reporter's current model of the Linux kernel, and an event being processed.

**Comment by neel** [comment]
If I understand correctly for a `close`  syscall (for example) the fd in `a0` is a necessary argument.  What I intend, is to add extra information as `args` attached with the syscall edge that will contain the a0 or associate this a0 with the edge in some other way. Afterwards I'll process it accordingly.

I am not requesting for a feature. I am looking for the part of the code which is responsible for picking the attributes or deriving the set of attributes that will be put on the edges.
