### ISSUE TITLE
spadeSocketBridge cannot connect to audispd socket

### ISSUE THREAD

**Issue by hungys** [ashish-gehani/SPADE#19]
I recently established an environment to run SPADE project for testing purpose, but no luck, I found that the Audit reporter didn't collect any log from Linux Audit, without any error log reported.

I then tried to run `lib/spadeSocketBridge` manually, and even if I executed it with root privilege, the program seems not able to connect to AF_UNIX socket of audispd. The error message shows:

```
./lib/spadeSocketBridge: Unable to connect to the socket. Error: Permission denied
```

To clarify, I have followed the instructions to set the permissions of `auditctl` and `lib/spadeSocketBridge`, and also set `active = yes` in `/etc/audisp/plugins.d/af_unix.conf`. My testing environment is Ubuntu 14.04 built with Vagrant (ubuntu/trusty64).

Thank you.

**Comment by ashish-gehani** [comment]
We tested this setup with Vagrant 1.7.4 and Ubuntu 14.04.

In the SPADE controller, we used:

> add storage Graphviz /tmp/audit.dot
> add reporter Audit

... Ran some activities on the system ...

> remove reporter Audit
> remove storage Graphviz

This resulted in a well-formed Graphviz /tmp/audit.dot file.
