### ISSUE TITLE
SPADE availibility

### ISSUE THREAD

**Issue by anaraserikbek** [ashish-gehani/SPADE#21]
Hello,
Is SPADE still available to use through cytobank to analyze flow cytometry data? I have not found the interactive online platform. 
And, in using SPADE through R, are there any other vignettes on using SPADE through R except the one that exists on SPADE's Bioconductor pages? 
Thank you

**Comment by ashish-gehani** [comment]
You are looking for a different SPADE.

See: http://pengqiu.gatech.edu/software/SPADE/
