### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by Wajihulhassan** [ashish-gehani/SPADE#24]
In "Available Filters" section of Wiki, change heading form "OPM2PROV" -> "OPM2Prov". Otherwise the user will assume that filter name is `OPM2PROV` and try to add filter using the command `add filter OPM2PROV position=1` which is certainly wrong because class name is `OPM2Prov`. 
https://github.com/ashish-gehani/SPADE/wiki/Available%20filters#opm2prov

**Comment by ashish-gehani** [comment]
Corrected. Thanks.
