### ISSUE TITLE
`make clean` remove uthash.h

### ISSUE THREAD

**Issue by Wajihulhassan** [ashish-gehani/SPADE#36]
Makefile has a following line: 
`@rm -rf src/spade/reporter/*.h lib/libLinuxFUSE.* lib/libMacFUSE.*`
which removes the necessary utash.h file which is necessary for compilation
`src/spade/reporter/uthash.h`

This leads to compilation error:
```
src/spade/reporter/spadeSocketBridge.c:237:20: fatal error: uthash.h: No such file or directory
 #include "uthash.h"
                    ^
compilation terminated.
make: *** [lib/spadeSocketBridge] Error 1
```

**Comment by ashish-gehani** [comment]
Makefile.in has been updated.
