### ISSUE TITLE
Trouble adding Neo4j graph database

### ISSUE THREAD

**Issue by jake77658** [ashish-gehani/SPADE#77]
When I try to run the command "add storage Neo4j /tmp/spade.graph_db" as described in the documentation, I get the error "Adding storage Neo4j... Unable to find/load class".

I can successfully add other storage such as Graphviz, and looking into the code has not helped. Any suggestions on how I might be able to fix this?

**Comment by sranasir** [comment]
Updated the code and wiki. Key-value pairs are required to add storages now.
Please use "add storage Neo4j databasePath=/tmp/spade.graph_db".
