### ISSUE TITLE
Graphviz Storage

### ISSUE THREAD

**Issue by bizzahbatool** [ashish-gehani/SPADE#83]
Can someone please tell why is this error coming
"spade.core.Kernel addCommand SEVERE: Unable to initialize storage!"

when I add Graphviz Storage with the following command:
add storage Graphviz outputFilePath=/tmp/provenance.dot

**Comment by BlueDrink9** [comment]
@bizzahbatool did you ever solve this? I'm having this issue as well.

```
May 27, 2020 5:04:28 PM spade.core.Kernel addCommand INFO: Adding storage: Graphviz
May 27, 2020 5:04:28 PM spade.storage.Graphviz initialize SEVERE: null
java.lang.NullPointerException
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:226)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:156)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:82)
	at spade.storage.Graphviz.initialize(Graphviz.java:76)
	at spade.core.Kernel.addCommand(Kernel.java:1019)
	at spade.core.Kernel.executeCommand(Kernel.java:670)
	at spade.core.Kernel$LocalControlConnection.run(Kernel.java:1889)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by BlueDrink9** [comment]
@ashish-gehani any thoughts?

**Comment by hassaanirshad** [comment]
Please use the Graphviz storage as described on the [wiki](https://github.com/ashish-gehani/SPADE/wiki/Creating-Graphviz-output).

**Comment by BlueDrink9** [comment]
@hassaanirshad yes, thank you, I've followed those instructions. However, I cannot add graphviz storage or reporting using the instructions there. I get the above stack trace in `spade debug` when I try to do so, with the same error as the original poster in `spade control`

**Comment by BlueDrink9** [comment]
I have installed graphviz, and it is available at the shell as `dot`. Are there other requirements for using the graphviz library?

I can successfully add Neo4j as storage, but not graphviz.

**Comment by hassaanirshad** [comment]
@BlueDrink9 Can you please share the SPADE control command that you are using to add the Graphviz storage?

**Comment by BlueDrink9** [comment]
`add storage Graphviz database=/Users/user/prov/output_prov.dot`

I've just solved my issue. User error, of course. I modified the neo4j command, not noticing that the argument `database` was changed for `output` when using graphviz. A poor interface in my opinion.

It would be great to have a more descriptive error in the case of incorrect arguments.

**Comment by BlueDrink9** [comment]
Thanks for your time

**Comment by BlueDrink9** [comment]
I would also like to note that when I tried `add reporter Graphviz /tmp/spade_prov.dot` yesterday (copied verbose from my terminal scrollback history), it failed. Trying again today, after first setting up the Graphviz storage and setting up openbsm reporting, the wiki command ` add reporter Graphviz /tmp/provenance.dot` worked fine.
