### ISSUE TITLE
Fails to build reporter on Ubuntu 16.04

### ISSUE THREAD

**Issue by ineart** [ashish-gehani/SPADE#84]
I am trying to build SPADE on Ubuntu 16.04. But i get fatal error during `make compile`. It occurs by SpadeAuditBridge compilation:
`src/spade/reporter/spadeAuditBridge.c:63:20: fatal error: uthash.h: No such file or directory`

![image](https://user-images.githubusercontent.com/44093146/52526803-fbb71980-2cbe-11e9-83dd-bc5f78947168.png)

**Comment by ashish-gehani** [comment]
It appears that you have not followed the steps described here (which includes installing the uthash package): https://github.com/ashish-gehani/SPADE/wiki/Requirements

**Comment by thesaad** [comment]
@ineart wereu able containerize SPADE or CamFlow. I can run on OS level but facing dependency issues in Dockerizing it
