### ISSUE TITLE
Read streaming data from Kafka

### ISSUE THREAD

**Issue by rainkin1993** [ashish-gehani/SPADE#86]
Hi,
The following is my scenario.
A collector generates **streaming** data and sends them to Kafka (a message queue). 
I want to create a SPADE report to read data from Kafka and leverage SPADE built-in Neo4j storage plugin to store data to Neo4j. Due to streaming data, the report can always obtain data from Kafka, thus will not stop. My goal is querying Neo4j during the report is still working.

My questions:

1. During reading data from Kafka, will SPADE  store data to Neo4j parallelly or start storing data to Neo4j after no data left in Kafka

2. It is possible to query Neo4j during SPADE is storing data to Neo4j?

Thanks.

**Comment by ashish-gehani** [comment]
Assuming you mean "SPADE Reporter" where you say "report", the answer to both questions is 'yes':

1. If you create a Reporter and add it to the running SPAKE Kernel (using the control client), it will run in a separate thread. So your Reporter could construct and send appropriate graph elements to the SPADE Kernel after each read from Kafka.

2. The Neo4j Storage can ingest new graph elements and be queried concurrently.

**Comment by rainkin1993** [comment]
Cool. Thanks very much for your quick reply.

I have two more questions:
1. If I want to query the Neo4j in the Reporter, which API should I use? spade.storage.Neo4j or spade.query.Neo4j ?
2. I just want to double check that Reporter and Neo4j Storage are two separate thread, thus SPADE can receive and store data parallelly?

Thanks again.

**Comment by ashish-gehani** [comment]
1. Currently, querying is only supported through the [SPADE query client](https://github.com/ashish-gehani/SPADE/wiki/Querying-SPADE). (The query surface is going to change in the coming months to support a richer set of primitives.)

2. Yes, they will run in different threads. Note that the Reporter sends data to the SPADE Kernel via a [programmatic interface](https://github.com/ashish-gehani/SPADE/wiki/Using-SPADE%27s-provenance-reporting-API). The SPADE Kernel sends it to all configured Storages. If you have added the Neo4j Storage the graph elements will go to it.
