### ISSUE TITLE
Not compatible with 32/64bit

### ISSUE THREAD

**Issue by hapablanha** [ashish-gehani/SPADE#87]
In spade\reporter\spadeAuditBridge.c, there are some program logic based on syscall no like 62. Obviously syscall has different meaning on X86 and X86_64, so SPADE looks not compatible with 64bit system?

Moreover, what is the OS distributions and kernel versions that has been tested using SPADE?

**Comment by ashish-gehani** [comment]
SPADE's Audit Reporter (that uses 'spadeAuditBridge') only works for x86_64 Linux. The code you pointed to works correctly on that platform.

Please see the Wiki for information about which platforms specific components run on.

**Comment by hapablanha** [comment]
I saw 32bit support was removed by this commit. What is the reason here?
https://github.com/ashish-gehani/SPADE/commit/a540bf1bf82209852d5920ebcab294488bfd1d91

**Comment by hassaanirshad** [comment]
The reason for removing that support was the auditing of a subset of system call using Linux kernel modules written for x86_64 Linux.

Can you please tell us what are you trying to do with SPADE in order to guide you better?

**Comment by hapablanha** [comment]
So SPADE support auditing a subset of system calls for X86_64, but it doesn't support the same for IA-32, correct?

I wonder if I can customize SPADE to output JSON format, and expect it has perfect compatibility.

**Comment by ashish-gehani** [comment]
Yes, that is correct.
