### ISSUE TITLE
make  error, what should I do?

### ISSUE THREAD

**Issue by testwill** [ashish-gehani/SPADE#88]
make --no-print-directory -f src/spade/reporter/audit/kernel-modules/Makefile
make -C /lib/modules/3.10.0-957.el7.x86_64/build M=/home/jack/code/spade/SPADE-tc-e5/src/spade/reporter/audit/kernel-modules modules
make: *** /lib/modules/3.10.0-957.el7.x86_64/build: No such file or directory.  Stop.
make[1]: *** [all] Error 2
make: *** [audit-kernel-module] Error

**Comment by hassaanirshad** [comment]
Hi,

It seems that the kernel headers are missing. Please double-check the instructions mentioned here (https://github.com/ashish-gehani/SPADE/wiki/Requirements) for your platform.

Thank you.
