### ISSUE TITLE
make error on Ubuntu 18.04

### ISSUE THREAD

**Issue by RayNCooper** [ashish-gehani/SPADE#89]
Hi there,
First of all: I really enjoy the concept of your project, but here's a little dealbreaker:

When trying to `make` on Ubuntu 18.04 I get the following error:
![Screenshot](https://user-images.githubusercontent.com/39743711/59277374-64f46c80-8c60-11e9-9e95-7ef61ea1c3d9.png)
 
Got any idea what might have gone wrong?
Edit: I already tried to install libelf-dev, nothing changed

**Comment by hassaanirshad** [comment]
Hi,

Thank you for opening the issue. Please do a 'git pull' to get the latest changes and build on Ubuntu 18.04.

Thank you.
