### ISSUE TITLE
PROV-O seems to be malformed

### ISSUE THREAD

**Issue by ruimaranhao** [ashish-gehani/SPADE#9]
SPADE produces invalid ttl files. For example, there are lots of close braces that have no matching open brace:

```
data:f25181be9786b40c9d3a880b3b9223816a5bd9eefc9861dafea8458710efb883 prov      data:type "WasTriggeredBy";
]; .
```

I've not tested PROV-N, but it might have the same issue.

**Comment by hassaanirshad** [comment]
SPADE works with OPM by default and to convert that to PROV model, OPM2Prov filter needs to be applied. Once the filter is added you should be able to generate correct ttl and provn files. 
Please add the mentioned filter before running any reporter using the following command: 'add filter OPM2Prov 0' where 0 is the index of the filter. 

Please let us know when you are able to correctly generate Prov storage output.

**Comment by ruimaranhao** [comment]
Is there any documentation on how to use the OPM2Prov filter?

Thanks.

**Comment by ruimaranhao** [comment]
It did generate PROV-O. I think the pull request still might make sense, though.

**Comment by hassaanirshad** [comment]
The following two links should help you regarding the use of filters in
SPADE:

https://github.com/ashish-gehani/SPADE/wiki/Available%20filters
https://github.com/ashish-gehani/SPADE/wiki/Using%20filters

Please let us know in case of any more queries.

Regards,
Hassaan

**Comment by hassaanirshad** [comment]
Good to know that it worked using that filter. About the code that you pointed to, the addition of the opening square brackets won't produce correct PROV-O if OPM2Prov filter isn't used. The Prov storage is simply not supposed to work with OPM. 

Adding a note on wiki about using OPM2Prov filter and closing the issue.

Thanks.
