### ISSUE TITLE
Does it support CentOS Linux release 7.6.1810 for CDM20

### ISSUE THREAD

**Issue by testwill** [ashish-gehani/SPADE#90]

**Comment by testwill** [comment]
Why do I need to add  Kernel modules to intercept and log

**Comment by ashish-gehani** [comment]
The 'tc-e5' CDM Storage was designed to run on Ubuntu 14.04 (with the Audit Reporter).

Kernel modules provide functionality needed for TC. The current 'master' branch does not use these by default.
