### ISSUE TITLE
On some low activity machine, it takes a bit too long to consume the events.

### ISSUE THREAD

**Issue by hapablanha** [ashish-gehani/SPADE#91]
By default REORDERING_WINDOW is 10000, the latency is too long (like 100-30 min). If we change it to 100, we wonder it will affect the traceability.
And to accommodate different client systems, this value may need to be dynamic.

                #define REORDERING_WINDOW 10000

		// if we have enough events in the buffer..
		while(HASH_COUNT(event_buf) > REORDERING_WINDOW)

**Comment by ashish-gehani** [comment]
This is a sliding window. If it is too small, events will be dropped when they arrive after the relevant window has passed. This will result in missing provenance elements.
