### ISSUE TITLE
Performance optimization for strlen in spadeAuditBridge.c

### ISSUE THREAD

**Issue by testwill** [ashish-gehani/SPADE#93]
for(cursor=0; cursor < strlen(buf); cursor++) {

Replace with the code below:

size_t buf_len = strlen(buf);

for(cursor=0; cursor < buf_len; cursor++) {

**Comment by ashish-gehani** [comment]
Thank you for identifying this optimization. Please can you submit it as a GitHub pull request?

**Comment by testwill** [comment]
ok
