### ISSUE TITLE
Unable to Connect To Socket- Setting up Auditor Reporter for Provence Collection Trouble Shooting

### ISSUE THREAD

**Issue by akul-goyal** [ashish-gehani/SPADE#96]
Hi, I am running ubuntu bionic 18.04 and trying to install SPADE. I followed the documentation to its exact installing the requirements and packages needed to run SPADE. Everything works fine from requirements, downloading, starting, collecting on linux, until I try to start real time collection. The error I get in the log file is listed below:

bin/spadeAuditBridge: Unable to connect to the socket: /var/run/audispd_events. Error: Connection refused

I have tried to run spadeAudtiBridge separately and I have faced the same issue. I have tried reinstalling the entire package but it still leaves me with the same error. I tried to install the socket manually for the package to connect but this is not work either.

**Comment by hassaanirshad** [comment]
Hi,
Can you please confirm the following two things:

1) You ran the commands 'sudo chown root bin/spadeAuditBridge' and 'sudo chmod ug+s bin/spadeAuditBridge' after building SPADE using the 'make' command?
2) The setuid-bit is set on the executable 'bin/spadeAuditBridge'?

Thank you,
Hassaan

**Comment by akul-goyal** [comment]
Hi Hassaan,

Yes to both questions.

Thanks,
Akul

**Comment by hassaanirshad** [comment]
Hi,

Thank you for confirming that.

Please share the output of the following commands:
1) ls -l bin/spadeAuditBridge
2) ls -l /var/run/audispd_events
3) grep "dispatcher" /etc/audit/auditd.conf
4) grep "active" /etc/audisp/plugins.d/af_unix.conf

Thank you,
Hassaan

**Comment by akul-goyal** [comment]
Hi,

1 . -rwsrwsr-x 1 root akulg2 124840 Oct  3 17:48 bin/spadeAuditBridge
2. -rw-rw-r-- 1 akulg2 akulg2 0 Oct  3 18:33 /var/run/audispd_events
3. initially : grep: /etc/audit/auditd.conf: Permission denied
    I ran under sudo and I got: dispatcher = /sbin/audispd
4. active = yes

Thanks,
Akul

**Comment by hassaanirshad** [comment]
Hi,

Thank you for sharing that. Everything seems fine except (2). Your Linux Audit Subsystem configuration seems to have an issue. The path '/var/run/audispd_events' should be a socket and not a regular file. In (2), it says that it is a regular file. Please try the following and see if the issue is resolved:

1) sudo service auditd stop
2) sudo rm /var/run/audispd_events
3) sudo service auditd start

The above steps would recreate the '/var/run/audispd_events' socket. You can make sure that it is a socket by running the 'ls -l' command.

Once that issue is resolved then please try running SPADE with all the required steps mentioned on wiki and you did before.

Thank you,
Hassaan

**Comment by akul-goyal** [comment]
Hey,
 After running sudo service auditd start the '/var/run/audispd_events' socket is not rebuilt. When trying to access that location I am getting a no file found error. I retried running Spade despite this and tried to built the auditor but it still wont work. 

Thanks,
Akul

**Comment by akul-goyal** [comment]
Hi,

I just retried the whole thing again and for some reason the socket is not getting built at /var/run/audispd_events. Is there a way to manually get this installed so that the system can run?

Thanks,
Akul

**Comment by hassaanirshad** [comment]
Hi,

Under default Linux Audit configuration (when 'af_unix' plugin is enabled), the socket '/var/run/audispd_events' is removed and recreated when the 'auditd' service is restarted.

The steps mentioned in the thread have been tested successfully on Ubuntu 18.04.

I would suggest reinstalling the Linux Audit Subsystem packages mentioned here: [SPADE Requirements](https://github.com/ashish-gehani/SPADE/wiki/Requirements)

And then following the configuration mentioned here: [SPADE Collecting Provenance](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Linux)

Or to find out more about Linux Audit configuration and what is incorrect in your setup, you can look into the man-pages for 'auditd.conf', 'audispd.conf', and 'audispd'.

Thank you,
Hassaan

**Comment by akul-goyal** [comment]
Hi,

So I reinstalled the packages and I am now getting an error when I try starting spade controller:

Error connecting to SPADE Kernel! javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: Certificate signature validation failed

Spade Controller wont start for me. And furthermore, /var/run/audispd_events does not exists either after running sudo service auditd start.

**Comment by hassaanirshad** [comment]
Hi,

Before continuing with using SPADE, please update your Linux Audit configuration where the state of your system should be the following post-configuration:

1) The processes 'kauditd', 'auditd', and 'audispd' should be running
2) The unix socket '/var/run/audispd_events' should be present and created by the Linux Audit Subsystem.

The steps to do that are mentioned [here](https://github.com/ashish-gehani/SPADE/wiki/Requirements) and [here](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Linux). 

Given your system is in correct state then please do the steps mentioned [here](https://github.com/ashish-gehani/SPADE/wiki/Collecting-system-wide-provenance-on-Linux) post-build of SPADE.

Finally, you can use SPADE using the instructions [here](https://github.com/ashish-gehani/SPADE/wiki/Starting-and-controlling-SPADE).

If any of those steps don't work on your system then please mention the step(s) for correction.

Thank you,
Hassaan

**Comment by akul-goyal** [comment]
Hey,

I reinstalled Ubuntu and redid the entire installation and I worked! Thank you for your help!

Thanks,
Akul

**Comment by hassaanirshad** [comment]
Glad to hear. Thank you for letting me know.
