### ISSUE TITLE
The provenance graph in Neo4j cannot correlate the process with the file.

### ISSUE THREAD

**Issue by WeiieW-cas** [ashish-gehani/SPADE#97]
Hi, I installed SPADE on CentOS7 and stored the result in Neo4j. I added reporter Audit fileIO=true. Then I used vim to create a new file F and to write several lines, save the file F. 
After that, I checked the provenance graph in Neo4j database. However, I cannot find the correlation between the process vim and the file F. Specifically, I started from the file F node, traversed the graph using BFS without concern of the edge direction. The BFS result is that I cannot find the vim process. Did I do something wrong?
Additionally, the node F's attributes contain the "permissions" which is '0000'. Is that normal?
Thanks.

**Comment by ashish-gehani** [comment]
As the Wiki pages indicate, we have worked with Ubuntu and Fedora. You may need to make changes for CentOS since the Audit output differs.
