### ISSUE TITLE
Failed to add a reporter

### ISSUE THREAD

**Issue by cssaheel** [ashish-gehani/SPADE#98]
Hello everyone,

I am new to SPADE, I have recorded a CSV log file from ProcMon, and I am trying to open it in an Ubuntu Linux box using SPADE  ProcMon reporter, but I am having trouble doing that:

> ~/SPADE/bin$ ./spade control
> 
> SPADE 3.0 Control Client
> 
> Available commands:
> 	add reporter|storage <class name> <initialization arguments>
> 	add analyzer|sketch <class name>
> 	add filter|transformer <class name> position=<number> <initialization arguments>
> 	remove reporter|analyzer|storage|sketch <class name>
> 	remove filter|transformer <position number>
> 	list reporters|storages|analyzers|filters|sketches|transformers|all
> 	config load|save <filename>
> 	exit
> 
> -> add reporter ProcMon /home/user/Desktop/Logfile.CSV
> **Adding reporter ProcMon... failed**

Thanks in advance!

**Comment by UnnameBao** [comment]
Did slove that problem? I meet the same trouble.

**Comment by UnnameBao** [comment]
Did you slove that problem? I meet the same trouble.

**Comment by ashish-gehani** [comment]
Look in ~/SPADE/log/

The log file provides more information.
